export const StarterCards = [
    //Green Diamonds
    {
    shape : "diamond",
    color : "green",
    number : 1,
    style : "outlined",
    path : "cards/green/dg1out.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 1,
    style : "solid",
    path : "cards/green/dg1sol.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 1,
    style : "stryped",
    path : "cards/green/dg1str.png",
    },

    {
    shape : "diamond",
    color : "green",
    number : 2,
    style : "outlined",
    path : "cards/green/dg2out.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 2,
    style : "solid",
    path : "cards/green/dg2sol.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 2,
    style : "stryped",
    path : "cards/green/dg2str.png",
    },

    {
    shape : "diamond",
    color : "green",
    number : 3,
    style : "outlined",
    path : "cards/green/dg3out.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 3,
    style : "solid",
    path : "cards/green/dg3sol.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 3,
    style : "stryped",
    path : "cards/green/dg3str.png",
    },

    //Green Ovals
    {
    shape : "oval",
    color : "green",
    number : 1,
    style : "outlined",
    path : "cards/green/og1out.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 1,
    style : "solid",
    path : "cards/green/og1sol.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 1,
    style : "stryped",
    path : "cards/green/og1str.png",
    },

    {
    shape : "oval",
    color : "green",
    number : 2,
    style : "outlined",
    path : "cards/green/og2out.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 2,
    style : "solid",
    path : "cards/green/og2sol.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 2,
    style : "stryped",
    path : "cards/green/og2str.png",
    },

    {
    shape : "oval",
    color : "green",
    number : 3,
    style : "outlined",
    path : "cards/green/og3out.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 3,
    style : "solid",
    path : "cards/green/og3sol.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 3,
    style : "stryped",
    path : "cards/green/og3str.png",
    },
    
    //Green Squiggles
    {
    shape : "squiggle",
    color : "green",
    number : 1,
    style : "outlined",
    path : "cards/green/sg1out.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 1,
    style : "solid",
    path : "cards/green/sg1sol.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 1,
    style : "stryped",
    path : "cards/green/sg1str.png",
    },

    {
    shape : "squiggle",
    color : "green",
    number : 2,
    style : "outlined",
    path : "cards/green/sg2out.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 2,
    style : "solid",
    path : "cards/green/sg2sol.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 2,
    style : "stryped",
    path : "cards/green/sg2str.png",
    },

    {
    shape : "squiggle",
    color : "green",
    number : 3,
    style : "outlined",
    path : "cards/green/sg3out.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 3,
    style : "solid",
    path : "cards/green/sg3sol.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 3,
    style : "stryped",
    path : "cards/green/sg3str.png",
    },
]

export const AdvancedCards = [
    //Green Diamonds
    {
    shape : "diamond",
    color : "green",
    number : 1,
    style : "outlined",
    path : "cards/green/dg1out.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 1,
    style : "solid",
    path : "cards/green/dg1sol.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 1,
    style : "stryped",
    path : "cards/green/dg1str.png",
    },

    {
    shape : "diamond",
    color : "green",
    number : 2,
    style : "outlined",
    path : "cards/green/dg2out.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 2,
    style : "solid",
    path : "cards/green/dg2sol.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 2,
    style : "stryped",
    path : "cards/green/dg2str.png",
    },

    {
    shape : "diamond",
    color : "green",
    number : 3,
    style : "outlined",
    path : "cards/green/dg3out.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 3,
    style : "solid",
    path : "cards/green/dg3sol.png",
    },
    {
    shape : "diamond",
    color : "green",
    number : 3,
    style : "stryped",
    path : "cards/green/dg3str.png",
    },

    //Purple Diamonds
    {
    shape : "diamond",
    color : "purple",
    number : 1,
    style : "outlined",
    path : "cards/purple/dp1out.png",
    },
    {
    shape : "diamond",
    color : "purple",
    number : 1,
    style : "solid",
    path : "cards/purple/dp1sol.png",
    },
    {
    shape : "diamond",
    color : "purple",
    number : 1,
    style : "stryped",
    path : "cards/purple/dp1str.png",
    },

    {
    shape : "diamond",
    color : "purple",
    number : 2,
    style : "outlined",
    path : "cards/purple/dp2out.png",
    },
    {
    shape : "diamond",
    color : "purple",
    number : 2,
    style : "solid",
    path : "cards/purple/dp2sol.png",
    },
    {
    shape : "diamond",
    color : "purple",
    number : 2,
    style : "stryped",
    path : "cards/purple/dp2str.png",
    },

    {
    shape : "diamond",
    color : "purple",
    number : 3,
    style : "outlined",
    path : "cards/purple/dp3out.png",
    },
    {
    shape : "diamond",
    color : "purple",
    number : 3,
    style : "solid",
    path : "cards/purple/dp3sol.png",
    },
    {
    shape : "diamond",
    color : "purple",
    number : 3,
    style : "stryped",
    path : "cards/purple/dp3str.png",
    },

    //Red Diamonds
    {
    shape : "diamond",
    color : "red",
    number : 1,
    style : "outlined",
    path : "cards/red/dr1out.png",
    },
    {
    shape : "diamond",
    color : "red",
    number : 1,
    style : "solid",
    path : "cards/red/dr1sol.png",
    },
    {
    shape : "diamond",
    color : "red",
    number : 1,
    style : "stryped",
    path : "cards/red/dr1str.png",
    },

    {
    shape : "diamond",
    color : "red",
    number : 2,
    style : "outlined",
    path : "cards/red/dr2out.png",
    },
    {
    shape : "diamond",
    color : "red",
    number : 2,
    style : "solid",
    path : "cards/red/dr2sol.png",
    },
    {
    shape : "diamond",
    color : "red",
    number : 2,
    style : "stryped",
    path : "cards/red/dr2str.png",
    },

    {
    shape : "diamond",
    color : "red",
    number : 3,
    style : "outlined",
    path : "cards/red/dr3out.png",
    },
    {
    shape : "diamond",
    color : "red",
    number : 3,
    style : "solid",
    path : "cards/red/dr3sol.png",
    },
    {
    shape : "diamond",
    color : "red",
    number : 3,
    style : "stryped",
    path : "cards/red/dr3str.png",
    },

    //Green Ovals
    {
    shape : "oval",
    color : "green",
    number : 1,
    style : "outlined",
    path : "cards/green/og1out.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 1,
    style : "solid",
    path : "cards/green/og1sol.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 1,
    style : "stryped",
    path : "cards/green/og1str.png",
    },

    {
    shape : "oval",
    color : "green",
    number : 2,
    style : "outlined",
    path : "cards/green/og2out.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 2,
    style : "solid",
    path : "cards/green/og2sol.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 2,
    style : "stryped",
    path : "cards/green/og2str.png",
    },

    {
    shape : "oval",
    color : "green",
    number : 3,
    style : "outlined",
    path : "cards/green/og3out.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 3,
    style : "solid",
    path : "cards/green/og3sol.png",
    },
    {
    shape : "oval",
    color : "green",
    number : 3,
    style : "stryped",
    path : "cards/green/og3str.png",
    },

    //Purple Ovals
    {
    shape : "oval",
    color : "purple",
    number : 1,
    style : "outlined",
    path : "cards/purple/op1out.png",
    },
    {
    shape : "oval",
    color : "purple",
    number : 1,
    style : "solid",
    path : "cards/purple/op1sol.png",
    },
    {
    shape : "oval",
    color : "purple",
    number : 1,
    style : "stryped",
    path : "cards/purple/op1str.png",
    },

    {
    shape : "oval",
    color : "purple",
    number : 2,
    style : "outlined",
    path : "cards/purple/op2out.png",
    },
    {
    shape : "oval",
    color : "purple",
    number : 2,
    style : "solid",
    path : "cards/purple/op2sol.png",
    },
    {
    shape : "oval",
    color : "purple",
    number : 2,
    style : "stryped",
    path : "cards/purple/op2str.png",
    },

    {
    shape : "oval",
    color : "purple",
    number : 3,
    style : "outlined",
    path : "cards/purple/op3out.png",
    },
    {
    shape : "oval",
    color : "purple",
    number : 3,
    style : "solid",
    path : "cards/purple/op3sol.png",
    },
    {
    shape : "oval",
    color : "purple",
    number : 3,
    style : "stryped",
    path : "cards/purple/op3str.png",
    },

    //Red Ovals
    {
    shape : "oval",
    color : "red",
    number : 1,
    style : "outlined",
    path : "cards/red/or1out.png",
    },
    {
    shape : "oval",
    color : "red",
    number : 1,
    style : "solid",
    path : "cards/red/or1sol.png",
    },
    {
    shape : "oval",
    color : "red",
    number : 1,
    style : "stryped",
    path : "cards/red/or1str.png",
    },

    {
    shape : "oval",
    color : "red",
    number : 2,
    style : "outlined",
    path : "cards/red/or2out.png",
    },
    {
    shape : "oval",
    color : "red",
    number : 2,
    style : "solid",
    path : "cards/red/or2sol.png",
    },
    {
    shape : "oval",
    color : "red",
    number : 2,
    style : "stryped",
    path : "cards/red/or2str.png",
    },

    {
    shape : "oval",
    color : "red",
    number : 3,
    style : "outlined",
    path : "cards/red/or3out.png",
    },
    {
    shape : "oval",
    color : "red",
    number : 3,
    style : "solid",
    path : "cards/red/or3sol.png",
    },
    {
    shape : "oval",
    color : "red",
    number : 3,
    style : "stryped",
    path : "cards/red/or3str.png",
    },

    //Green Squiggles
    {
    shape : "squiggle",
    color : "green",
    number : 1,
    style : "outlined",
    path : "cards/green/sg1out.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 1,
    style : "solid",
    path : "cards/green/sg1sol.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 1,
    style : "stryped",
    path : "cards/green/sg1str.png",
    },

    {
    shape : "squiggle",
    color : "green",
    number : 2,
    style : "outlined",
    path : "cards/green/sg2out.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 2,
    style : "solid",
    path : "cards/green/sg2sol.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 2,
    style : "stryped",
    path : "cards/green/sg2str.png",
    },

    {
    shape : "squiggle",
    color : "green",
    number : 3,
    style : "outlined",
    path : "cards/green/sg3out.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 3,
    style : "solid",
    path : "cards/green/sg3sol.png",
    },
    {
    shape : "squiggle",
    color : "green",
    number : 3,
    style : "stryped",
    path : "cards/green/sg3str.png",
    },

    //Purple Squiggles
    {
    shape : "squiggle",
    color : "purple",
    number : 1,
    style : "outlined",
    path : "cards/purple/sp1out.png",
    },
    {
    shape : "squiggle",
    color : "purple",
    number : 1,
    style : "solid",
    path : "cards/purple/sp1sol.png",
    },
    {
    shape : "squiggle",
    color : "purple",
    number : 1,
    style : "stryped",
    path : "cards/purple/sp1str.png",
    },

    {
    shape : "squiggle",
    color : "purple",
    number : 2,
    style : "outlined",
    path : "cards/purple/sp2out.png",
    },
    {
    shape : "squiggle",
    color : "purple",
    number : 2,
    style : "solid",
    path : "cards/purple/sp2sol.png",
    },
    {
    shape : "squiggle",
    color : "purple",
    number : 2,
    style : "stryped",
    path : "cards/purple/sp2str.png",
    },

    {
    shape : "squiggle",
    color : "purple",
    number : 3,
    style : "outlined",
    path : "cards/purple/sp3out.png",
    },
    {
    shape : "squiggle",
    color : "purple",
    number : 3,
    style : "solid",
    path : "cards/purple/sp3sol.png",
    },
    {
    shape : "squiggle",
    color : "purple",
    number : 3,
    style : "stryped",
    path : "cards/purple/sp3str.png",
    },

    //Red Squiggles
    {
    shape : "squiggle",
    color : "red",
    number : 1,
    style : "outlined",
    path : "cards/red/sr1out.png",
    },
    {
    shape : "squiggle",
    color : "red",
    number : 1,
    style : "solid",
    path : "cards/red/sr1sol.png",
    },
    {
    shape : "squiggle",
    color : "red",
    number : 1,
    style : "stryped",
    path : "cards/red/sr1str.png",
    },

    {
    shape : "squiggle",
    color : "red",
    number : 2,
    style : "outlined",
    path : "cards/red/sr2out.png",
    },
    {
    shape : "squiggle",
    color : "red",
    number : 2,
    style : "solid",
    path : "cards/red/sr2sol.png",
    },
    {
    shape : "squiggle",
    color : "red",
    number : 2,
    style : "stryped",
    path : "cards/red/sr2str.png",
    },

    {
    shape : "squiggle",
    color : "red",
    number : 3,
    style : "outlined",
    path : "cards/red/sr3out.png",
    },
    {
    shape : "squiggle",
    color : "red",
    number : 3,
    style : "solid",
    path : "cards/red/sr3sol.png",
    },
    {
    shape : "squiggle",
    color : "red",
    number : 3,
    style : "stryped",
    path : "cards/red/sr3str.png",
    },
]